# Project information
site_name: OTUS_COURSE_PAPER

# Repository
repo_name: 1 
repo_url: 2

site_url: https://maxpothier1990.github.io/OTUS_course_paper/

theme:
  name: material
  palette:
	  primary: teal
    
  font:
    text: Roboto
    code: Roboto Mono
  language: ru
  features:
    - navigation.instant # Мгновенная загрузка
    - navigation.tracking # Когда отслеживание привязки включено, URL-адрес в адресной строке автоматически обновляется активным привязкой, как выделено в оглавлении. 
    - navigation.expand # Автоматическое открытие подразделов на панели слева
    - navigation.path # Над заголовком каждой страницы отображается путь
    - navigation.top # Кнопка «назад-вверх»
    - navigation.footer # Переключение кнопками предыдущей/следующей страницы в футере
    - navigation.tabs # Навигационные вкладки
    # - navigation.sections # Отображение верхних вкладок на панели слева
    - navigation.indexes # Скрыть дублирование заголовка на панели слева.
    - toc.integrate # Интеграция подразделов в панель слева
    - toc.follow # Автоматическая прокрутка боковой панели при прокрутке
    - search.highlight # Подсветка вхождений в тексте
    - search.suggest # Автозавершение поискового запроса
    - content.code.copy # Кнопка копирования кода

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - bpmn-js
  - search:
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
  - swagger-ui-tag
  - build_plantuml:
      render: 'server' # or "local" for local rendering
      bin_path: '/usr/local/bin/plantuml' # ignored when render: server
      server: 'http://www.plantuml.com/plantuml' # official plantuml server
      disable_ssl_certificate_validation: true # for self-signed and invalid certs
      output_format: 'svg' # or "png"
      diagram_root: 'docs/diagrams' # should reside under docs_dir
      output_folder: 'out'
      input_folder: 'src'
      input_extensions: '' # comma separated list of extensions to parse, by default every file is parsed
  - enumerate-headings:
      exclude:
        - index.md
        - glossary.md

nav:
  - Домашняя страница:
    - index.md
  - Документация:
    - glossary.md
    - general info.md
    - goals.md
    - characteristics.md
    - business process.md
    - requirements.md
    - model.md
    - architecture.md
    - uiux.md
    - api.md
  - Задачи:
    